'use server';

import { Octokit } from '@octokit/rest';

export interface FileData {
    path: string;
    content: string;
}

export async function createGitHubRepo(
    projectName: string,
    files: FileData[],
    userGitHubToken: string
): Promise<string> {
    const octokit = new Octokit({ auth: userGitHubToken });

    try {
        // Create the repository
        const { data: repo } = await octokit.repos.createForAuthenticatedUser({
            name: projectName,
            description: 'Generated by AI Project Generator',
            private: false,
            auto_init: true,
        });

        console.log(`📦 Repository created: ${repo.html_url}`);

        // Wait briefly for GitHub to initialize the repo
        await new Promise((res) => setTimeout(res, 2000));

        // Upload each file sequentially
        for (const file of files) {
            console.log(`📝 Uploading ${file.path}...`);
            await octokit.repos.createOrUpdateFileContents({
                owner: repo.owner.login,
                repo: repo.name,
                path: file.path,
                message: `Add ${file.path}`,
                content: Buffer.from(file.content).toString('base64'),
            });
        }

        console.log('✅ All files uploaded successfully!');
        return repo.html_url;
    } catch (error: any) {
        console.error('GitHub Error:', error.message);
        if (error.response?.data) {
            console.error('🔍 GitHub Response:', error.response.data);
        }
        throw new Error(`Failed to create or update repo: ${error.message}`);
    }
}